{% set version = "1.0.2" %}
{% set exec = "apptainer" %}

package:
  name: {{ exec }}
  version: {{ version }}

source:
  - folder: src/github.com/apptainer/{{ exec }}
    url: https://github.com/apptainer/{{ exec }}/releases/download/v{{ version }}/{{ exec }}-{{ version }}.tar.gz
    sha256: 2d7a9d0a76d5574459d249c3415e21423980d9154ce85e8c34b0600782a7dfd3
    patches:
      - patches/0001-set-version-from-env.diff
      - patches/0002-squashfs-tools-apptainer-conf.diff
      - patches/0003-use-external-CNI.diff
build:
  number: 1
  skip: true  # [not linux]
  # The binary is made runtime relocatable using the included patch
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - go-cgo >=1.18
    - sysroot_linux-64
    - libuuid
    - gpgme
    - libseccomp
    - pkg-config
    - git
    - make
    - sed
  host:
    - conda-forge::glib
    - conda-forge::openssl
    - conda-forge::libarchive
    - conda-forge::libseccomp  # [linux]
    - conda-forge::libuuid  # [linux]
    - conda-forge::patchelf
  run:
    - conda-forge::cni-plugins >=1.0
    - conda-forge::glib
    - conda-forge::libarchive
    - conda-forge::libseccomp  # [linux]
    - conda-forge::libuuid  # [linux]
    - conda-forge::openssl
    - conda-forge::patchelf
    - conda-forge::squashfs-tools >=4.4  # [linux]

test:
  commands:
    - {{ exec }} --help
    - {{ exec }} --version
    - {{ exec }} --version | grep {{ version }}

    # Ensure we are using conda's CNI
    - test ! -d $PREFIX/libexec/{{ exec }}/cni
    - test -d $PREFIX/lib/cni

    - test ! -d $PREFIX/etc/{{ exec }}/network
    - test -f $PREFIX/etc/cni/net.d/00_bridge.conflist

about:
  home: https://apptainer.org/
  license: BSD-3
  license_file: src/github.com/apptainer/apptainer/LICENSE.md
  summary: 'Apptainer: Application containers for Linux'

  description: |
    Apptainer is a container platform focused on supporting "Mobility of
    Compute"

    Mobility of Compute encapsulates the development to compute model where
    developers can work in an environment of their choosing and creation and
    when the developer needs additional compute resources, this environment
    can easily be copied and executed on other platforms. Additionally as the
    primary use case for Apptainer is targeted towards computational
    portability, many of the barriers to entry of other container solutions do
    not apply to Apptainer making it an ideal solution for users (both
    computational and non-computational) and HPC centers.

  dev_url: https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md
  dev_url: https://github.com/phupe/conda-pkg-apptainer
  doc_url: https://apptainer.org/docs

extra:
  recipe-maintainers:
    - phupe
