{% set version = "1.1.8" %}
{% set exec = "apptainer" %}

package:
  name: {{ exec }}
  version: {{ version }}

source:
  - folder: src/github.com/apptainer/{{ exec }}
    url: https://github.com/apptainer/{{ exec }}/releases/download/v{{ version }}/{{ exec }}-{{ version }}.tar.gz
    sha256: dafb195aa483aac309ec8ed4fcfa3b1202b9b2580a70bf0a7d8291b5bdf7c432 
    patches:
      - patches/0003-use-external-CNI.diff
build:
  number: 1
  skip: true  # [not linux]
  # The binary is made runtime relocatable using the included patch
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - go-cgo >=1.18
    - sysroot_linux-64
    - libuuid
    - gpgme
    - libseccomp
    - pkg-config
    - git
    - make
    - sed
  host:
    - conda-forge::glib
    - conda-forge::openssl
    - conda-forge::libarchive
    - conda-forge::libseccomp  # [linux]
    - conda-forge::libuuid  # [linux]
    - conda-forge::squashfs-tools >=4.4  # [linux]
    - conda-forge::squashfuse  # [linux]
  run:
    - conda-forge::cni-plugins >=1.0
    - conda-forge::glib
    - conda-forge::libarchive
    - conda-forge::libseccomp  # [linux]
    - conda-forge::libuuid  # [linux]
    - conda-forge::openssl
    - conda-forge::squashfs-tools >=4.4  # [linux]
    - conda-forge::squashfuse  # [linux]

test:
  commands:
    - {{ exec }} --help
    - {{ exec }} --version
    - {{ exec }} --version | grep {{ version }}

    # Ensure we are using conda's CNI
    - test ! -d $PREFIX/libexec/{{ exec }}/cni
    - test -d $PREFIX/lib/cni

    - test ! -d $PREFIX/etc/{{ exec }}/network
    - test -f $PREFIX/etc/cni/net.d/00_bridge.conflist

about:
  home: https://apptainer.org/
  license: BSD-3-Clause
  license_file: src/github.com/apptainer/apptainer/LICENSE.md
  summary: 'Apptainer: Application containers for Linux'

  description: |
    Apptainer is a container platform focused on supporting "Mobility of
    Compute"

    Mobility of Compute encapsulates the development to compute model where
    developers can work in an environment of their choosing and creation and
    when the developer needs additional compute resources, this environment
    can easily be copied and executed on other platforms. Additionally as the
    primary use case for Apptainer is targeted towards computational
    portability, many of the barriers to entry of other container solutions do
    not apply to Apptainer making it an ideal solution for users (both
    computational and non-computational) and HPC centers.

  dev_url: https://github.com/apptainer/apptainer/blob/main/CONTRIBUTING.md
  dev_url: https://github.com/phupe/conda-pkg-apptainer
  doc_url: https://apptainer.org/docs

extra:
  recipe-maintainers:
    - phupe
